---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
    exclude_paths:
    - Gemfile.lock
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
    - spec/**/*
    - db/**/*
    config:
      languages:
        ruby:
          mass_threshold: 28
        javascript:
          mass_threshold: 40
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.slim"
  - "**.rb"
  - "**.slim"
  - "**.css"
  - "**.scss"
  - "**.coffee"
  - "**.js"
exclude_paths:
- script/**/*
- vendor/**/*
